### ISSUE TITLE
Allow Comments

### ISSUE THREAD

**Issue by GochoMugo** [cmisenas/cmisenas.github.io#1]
You should consider adding a comments section on your blog. I am finding your blog rather refreshing. Kudos to that!!! :+1: And a comments section would really help ensure you keep your word of writing blog posts more often.

**Comment by cmisenas** [comment]
Thanks @GochoMugo !! I really appreciate that and any feedback about it (I wasn't even sure how people would find my blog. :smile:  ) as I'm new to keeping a blog.

And thanks for reminding me about adding a comments section. :+1:

**Comment by GochoMugo** [comment]
I also just started my blog at https://gochomugo.github.io. People always find a way of getting great content! Press on! :muscle:
